### ISSUE TITLE
Feature request: Keyboard shortcut for Freeze & Flatten function

### ISSUE THREAD

**Issue by Smopraq** [jastro-dev/LiveEnhancementSuite-Live12#1]
Hi, first of all: Thank you!  Your fork works flawlessly with 12 suite, and already contains some fixes and workarounds I desperatly wanted.

2nd, I have a request: Ableton 12 introduced the combined function: "Freeze & Flatten", a render in place if you wil. That was about time.  Now it would have been great if they added a keyboard shortcut from the get go but I guess thats probably due for Ableton 13.

I'd like to suggest addding a keyboard shortcut for this function, e.g: Ctrl+Alt+F.

![image](https://github.com/jastro-dev/LiveEnhancementSuite-Live12/assets/39970025/63335c63-0b14-4b40-bb1c-89a4b411c209)

**Comment by jastro-dev** [comment]
I figured out if you hit ALT+SHIFT+F on a track it'll go straight to flattening it.

**Comment by jer-castro** [comment]
![Recording 2024-03-13 at 11 46 42](https://github.com/jastro-dev/LiveEnhancementSuite-Live12/assets/160854558/27636f82-cdb2-4e2c-a0dc-00771d9546ec)
Works if you use ALT+SHIFT+F in the current build.
