### ISSUE TITLE
Double Redo Issue (Ctl + Shift + Z)

### ISSUE THREAD

**Issue by JustinRR92** [jastro-dev/LiveEnhancementSuite-Live12#3]
#### **Description:**

When using (Ctrl + Shift + Z) to Redo steps on Windows, the Redo action is executed twice consecutively, resulting in the incorrect state being restored.

#### **Steps to Reproduce:**

1. Drop an audio sample into the arrangement view for an audio track.
2. Select the audio track and duplicate it multiple times.
3. Undo some of the duplications.
4. Attempt to Redo those steps using (Ctrl + Shift + Z).
5. Notice that the Redo brings back two duplicates at a time instead of one.

#### **Expected Behavior:**

Redo should only restore one duplication at a time.

#### **Actual Behavior:**

Redo restores two duplications at a time.

#### **Environment:**

Ableton Live 12 Suite - 12.0.2 (Build: 2024-04-09_491da1ed88)
Windows 11 64-bit

#### **Additional Comments:**

---
Dude, thank you so much for fixing this for A12. I'm so happy I found this as I have been using LES for years. You are a lifesaver for fixing this. If possible to fix this Redo issue—this has been the only problem I've found thus far, it would mean a lot. I've only been using your version of LES with the menu for 2 hours so far. Thanks for everything!

---

**Comment by jastro-dev** [comment]
Hey! I was able to get release a fix for this issue. I've gotten so used to this problem since older Live versions that it never occurred to me to look into it. Thanks!
